/** @file
  Configuration Manager Dxe

  Copyright (c) 2017, ARM Limited. All rights reserved.

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

  @par Glossary:
    - Cm or CM   - Configuration Manager
    - Obj or OBJ - Object
**/

#include <Library/DebugLib.h>
#include <Library/PcdLib.h>
#include <Library/ArmLib.h>
#include <Library/UefiBootServicesTableLib.h>
#include <IndustryStandard/Acpi.h>
#include <IndustryStandard/Smbios.h>

#include <DynamicTables/TableGenerator.h>
#include <DynamicTables/AcpiTableGenerator.h>
#include <DynamicTables/SmbiosTableGenerator.h>
#include <DynamicTables/StandardNameSpaceObjects.h>
#include <DynamicTables/ConfigurationManagerObject.h>
#include <DynamicTables/StandardNameSpaceObjects.h>
#include <DynamicTables/ArmNameSpaceObjects.h>
#include <Protocol/ConfigurationManagerProtocol.h>
#include "Platform.h"
#include "ConfigurationManager.h"

// AML Code Include files generated by iASL Compiler
#include <Dsdt.hex>

/** A macro to define the configuration manager version.
*/
#define CONFIGURATION_MANAGER_REVISION CREATE_REVISION (1, 0)

/** A macro describing the OEM ID.
*/
#define CFG_MGR_OEM_ID    { 'A', 'R', 'M', 'L', 'T', 'D' }

/** A structure describing the platform configuration
    manager repository information.
*/
typedef struct PlatformRepositoryInfo {
  /// Configuration Manager Information
  CM_STD_OBJ_CONFIGURATION_MANAGER_INFO  CmInfo;

  /// List of ACPI tables
  CM_STD_OBJ_ACPI_TABLE_INFO             CmAcpiTableList[6];

  /// Boot architecture information
  CM_ARM_BOOT_ARCH_INFO                  BootArchInfo;

  /// Power management profile information
  CM_ARM_POWER_MANAGEMENT_PROFILE_INFO   PmProfileInfo;

  /// GIC CPU interface information
  CM_ARM_GICC_INFO                       GicCInfo[8];

  /// GIC distributor information
  CM_ARM_GICD_INFO                       GicDInfo;

  /// GIC Redistributor information
  CM_ARM_GIC_REDIST_INFO                 GicRedistInfo;

  /// Generic timer information
  CM_ARM_GENERIC_TIMER_INFO              GenericTimerInfo;

  /// Generic timer block information
  CM_ARM_GTBLOCK_INFO                    GTBlockInfo[1];

  /// Generic timer frame information
  CM_ARM_GTBLOCK_TIMER_FRAME_INFO        GTBlock0TimerInfo[2];

  /// Watchdog information
  CM_ARM_GENERIC_WATCHDOG_INFO           Watchdog;

  /// Serial port information for the
  /// serial port console redirection port.
  CM_ARM_SERIAL_PORT_INFO                SpcrSerialPort;

  /// Serial port information for the
  /// DBG2 UART port
  CM_ARM_SERIAL_PORT_INFO                DbgSerialPort;

  /// GIC ITS information
  CM_ARM_GIC_ITS_INFO                    GicItsInfo;
} EFI_PLATFORM_REPOSITORY_INFO;

/** The platform configuration repository information.
*/
EFI_PLATFORM_REPOSITORY_INFO ArmVExpressPlatformRepositoryInfo = {
  /// Configuration Manager information
  { CONFIGURATION_MANAGER_REVISION, CFG_MGR_OEM_ID },

  // ACPI Table List
  {
    // FADT Table
    {
      EFI_ACPI_6_1_FIXED_ACPI_DESCRIPTION_TABLE_SIGNATURE,
      CREATE_STD_ACPI_TABLE_GEN_ID (ESTD_ACPI_TABLE_ID_FADT),
      NULL
    },
    // GTDT Table
    {
      EFI_ACPI_6_1_GENERIC_TIMER_DESCRIPTION_TABLE_SIGNATURE,
      CREATE_STD_ACPI_TABLE_GEN_ID (ESTD_ACPI_TABLE_ID_GTDT),
      NULL
    },
    // MADT Table
    {
      EFI_ACPI_6_1_MULTIPLE_APIC_DESCRIPTION_TABLE_SIGNATURE,
      CREATE_STD_ACPI_TABLE_GEN_ID (ESTD_ACPI_TABLE_ID_MADT),
      NULL
    },
    // SPCR Table
    {
      EFI_ACPI_6_1_SERIAL_PORT_CONSOLE_REDIRECTION_TABLE_SIGNATURE,
      CREATE_STD_ACPI_TABLE_GEN_ID (ESTD_ACPI_TABLE_ID_SPCR),
      NULL
    },
    // DSDT Table
    {
      EFI_ACPI_6_1_DIFFERENTIATED_SYSTEM_DESCRIPTION_TABLE_SIGNATURE,
      CREATE_STD_ACPI_TABLE_GEN_ID (ESTD_ACPI_TABLE_ID_DSDT),
      (EFI_ACPI_DESCRIPTION_HEADER*)DsdtAmlCode
    },
    // DBG2 Table
    {
      EFI_ACPI_6_1_DEBUG_PORT_2_TABLE_SIGNATURE,
      CREATE_STD_ACPI_TABLE_GEN_ID (ESTD_ACPI_TABLE_ID_DBG2),
      NULL
    }
  },

  // Boot architecture information
  { EFI_ACPI_6_1_ARM_PSCI_COMPLIANT },              // BootArchFlags

  // Power management profile information
  { EFI_ACPI_6_1_PM_PROFILE_ENTERPRISE_SERVER },    // PowerManagement Profile

  // GIC CPU Interface information
  {
    GICC_ENTRY (0, GET_MPID (0, 0), 92, 25),
    GICC_ENTRY (1, GET_MPID (0, 1), 93, 25),
    GICC_ENTRY (2, GET_MPID (0, 2), 94, 25),
    GICC_ENTRY (3, GET_MPID (0, 3), 95, 25),

    GICC_ENTRY (4, GET_MPID (1, 0), 96, 25),
    GICC_ENTRY (5, GET_MPID (1, 1), 97, 25),
    GICC_ENTRY (6, GET_MPID (1, 2), 98, 25),
    GICC_ENTRY (7, GET_MPID (1, 3), 99, 25)
  },

  // GIC Distributor Info
  {
    0,                                      // UINT32  GicId
    FixedPcdGet64 (PcdGicDistributorBase),  // UINT64  PhysicalBaseAddress
    0,                                      // UINT32  SystemVectorBase
    3                                       // UINT8   GicVersion
  },


  /// GIC Re-Distributor Info
  {
    // UINT64  DiscoveryRangeBaseAddress
    FixedPcdGet64 (PcdGicRedistributorsBase),
    // UINT32  DiscoveryRangeLength
    0x00200000
  },

  // Generic Timer Info
  {
    FVP_SYSTEM_TIMER_BASE_ADDRESS,
    FVP_CNT_READ_BASE_ADDRESS,
    FixedPcdGet32 (PcdArmArchTimerSecIntrNum),
    FVP_GTDT_GTIMER_FLAGS,
    FixedPcdGet32 (PcdArmArchTimerIntrNum),
    FVP_GTDT_GTIMER_FLAGS,
    FixedPcdGet32 (PcdArmArchTimerVirtIntrNum),
    FVP_GTDT_GTIMER_FLAGS,
    FixedPcdGet32 (PcdArmArchTimerHypIntrNum),
    FVP_GTDT_GTIMER_FLAGS
  },

  // Generic Timer Block Information
  {
    {
      FVP_GT_BLOCK_CTL_BASE,
      FVP_TIMER_FRAMES_COUNT,
      (CM_ARM_GTBLOCK_TIMER_FRAME_INFO*)((UINT8*)&ArmVExpressPlatformRepositoryInfo +
        OFFSET_OF (EFI_PLATFORM_REPOSITORY_INFO, GTBlock0TimerInfo))
    }
  },

  // GT Block Timer Frames
  {
    // Frame 0
    {
      0,                                //UINT8   FrameNumber
      FVP_GT_BLOCK_FRAME0_CTL_BASE,     //UINT64  PhysicalAddressCntBase
      FVP_GT_BLOCK_FRAME0_CTL_EL0_BASE, //UINT64  PhysicalAddressCntEL0Base
      FVP_GT_BLOCK_FRAME0_GSIV,         //UINT32  PhysicalTimerGSIV
      FVP_GTX_TIMER_FLAGS,              //UINT32  PhysicalTimerFlags
      0,                                //UINT32  VirtualTimerGSIV
      0,                                //UINT32  VirtualTimerFlags
      FVP_GTX_COMMON_FLAGS              //UINT32  CommonFlags
    },
    // Frame 1
    {
      1,                                //UINT8   FrameNumber
      FVP_GT_BLOCK_FRAME1_CTL_BASE,     //UINT64  PhysicalAddressCntBase
      FVP_GT_BLOCK_FRAME1_CTL_EL0_BASE, //UINT64  PhysicalAddressCntEL0Base
      FVP_GT_BLOCK_FRAME1_GSIV,         //UINT32  PhysicalTimerGSIV
      FVP_GTX_TIMER_FLAGS,              //UINT32  PhysicalTimerFlags
      0,                                //UINT32  VirtualTimerGSIV
      0,                                //UINT32  VirtualTimerFlags
      FVP_GTX_COMMON_FLAGS              //UINT32  CommonFlags
    },
  },

  // Watchdog Info
  {
    FixedPcdGet64 (PcdGenericWatchdogControlBase),
    FixedPcdGet64 (PcdGenericWatchdogRefreshBase),
    FixedPcdGet32 (PcdGenericWatchdogEl2IntrNum),
    FVP_SBSA_WATCHDOG_FLAGS
  },

  // SPCR Serial Port
  {
    FixedPcdGet64 (PcdSerialRegisterBase),  // UINT64  BaseAddress
    FixedPcdGet32 (PL011UartInterrupt),     // UINT32  Interrupt
    FixedPcdGet64 (PcdUartDefaultBaudRate), // UINT64  BaudRate
    FixedPcdGet32 (PL011UartClkInHz)        // UINT32  Clock
  },
  // Debug Serial Port
  {
    FixedPcdGet64 (PcdSerialDbgRegisterBase), // UINT64  BaseAddress
    38,                                       // UINT32  Interrupt
    FixedPcdGet64 (PcdSerialDbgUartBaudRate), // UINT64  BaudRate
    FixedPcdGet32 (PcdSerialDbgUartClkInHz)   // UINT32  Clock
  },

  // GIC ITS
  {
    // The GIC ITS ID.
    0,

    // The physical address for the
    // Interrupt Translation Service
    0x2f020000
  }
};

/** Initialize the platform configuration repository.

    @param [in]  This        Poiner to the Configuration Manager Protocol.

    @retval
      EFI_SUCCESS   Success
*/
STATIC
EFI_STATUS
EFIAPI
InitializePlatformRepository (
  IN  CONST EFI_CONFIGURATION_MANAGER_PROTOCOL  * CONST This
  )
{
  return EFI_SUCCESS;
}

/** Return a standard namespace object.

    @param [in]  This        Poiner to the Configuration Manager Protocol.
    @param [in]  CmObjectId  The Configuration Manager Object ID.
    @param [out] CmObject    Pointer to the Configuration Manager Object
                             descrptor describing the requested Object.

    @retval Returns:
      EFI_SUCCESS           Success.
      EFI_INVALID_PARAMETER A parameter is invalid.
      EFI_NOT_FOUND         The required object information is not found.
*/
EFI_STATUS
EFIAPI
GetStandardNameSpaceObject (
  IN  CONST EFI_CONFIGURATION_MANAGER_PROTOCOL  * CONST This,
  IN  CONST CM_OBJECT_ID                                CmObjectId,
  IN  OUT   CM_OBJ_DESCRIPTOR                   * CONST CmObject
  )
{
  EFI_STATUS                      Status = EFI_SUCCESS;
  EFI_PLATFORM_REPOSITORY_INFO  * PlatformRepo;

  if ((This == NULL) || (CmObject == NULL)) {
    ASSERT (This != NULL);
    ASSERT (CmObject != NULL);
    return EFI_INVALID_PARAMETER;
  }
  PlatformRepo = This->PlatRepoInfo;

  switch (GET_CM_OBJECT_ID (CmObjectId)) {
    HANDLE_CM_OBJECT (EStdObjCfgMgrInfo, PlatformRepo->CmInfo);
    HANDLE_CM_OBJECT (EStdObjAcpiTableList, PlatformRepo->CmAcpiTableList);
    default: {
      Status = EFI_NOT_FOUND;
      DEBUG ((
        DEBUG_ERROR,
        "ERROR: Object 0x%x. Status = %r\n",
        CmObjectId,
        Status
        ));
      break;
    }
  }

  return Status;
}

/** Return an ARM namespace object.

    @param [in]  This        Poiner to the Configuration Manager Protocol.
    @param [in]  CmObjectId  The Configuration Manager Object ID.
    @param [out] CmObject    Pointer to the Configuration Manager Object
                             descrptor describing the requested Object.

    @retval Returns:
      EFI_SUCCESS           Success.
      EFI_INVALID_PARAMETER A parameter is invalid.
      EFI_NOT_FOUND         The required object information is not found.
*/
EFI_STATUS
EFIAPI
GetArmNameSpaceObject (
  IN  CONST EFI_CONFIGURATION_MANAGER_PROTOCOL  * CONST This,
  IN  CONST CM_OBJECT_ID                                CmObjectId,
  IN  OUT   CM_OBJ_DESCRIPTOR                   * CONST CmObject
  )
{
  EFI_STATUS                      Status = EFI_SUCCESS;
  EFI_PLATFORM_REPOSITORY_INFO  * PlatformRepo;

  if ((This == NULL) || (CmObject == NULL)) {
    ASSERT (This != NULL);
    ASSERT (CmObject != NULL);
    return EFI_INVALID_PARAMETER;
  }
  PlatformRepo = This->PlatRepoInfo;

  switch (GET_CM_OBJECT_ID (CmObjectId)) {
    HANDLE_CM_OBJECT (EArmObjBootArchInfo, PlatformRepo->BootArchInfo);
    HANDLE_CM_OBJECT (
      EArmObjPowerManagementProfileInfo,
      PlatformRepo->PmProfileInfo
      );
    HANDLE_CM_OBJECT (EArmObjGenericTimerInfo, PlatformRepo->GenericTimerInfo);
    HANDLE_CM_OBJECT (
      EArmObjPlatformGenericWatchdogInfo,
      PlatformRepo->Watchdog
      );
    HANDLE_CM_OBJECT (EArmObjPlatformGTBlockInfo, PlatformRepo->GTBlockInfo);
    HANDLE_CM_OBJECT (EArmObjGicCInfo, PlatformRepo->GicCInfo);
    HANDLE_CM_OBJECT (EArmObjGicDInfo, PlatformRepo->GicDInfo);
    HANDLE_CM_OBJECT (
      EArmObjGicRedistributorInfo,
      PlatformRepo->GicRedistInfo
      );
    HANDLE_CM_OBJECT (
      EArmObjSerialConsolePortInfo,
      PlatformRepo->SpcrSerialPort
      );
    HANDLE_CM_OBJECT (EArmObjSerialDebugPortInfo, PlatformRepo->DbgSerialPort);
    HANDLE_CM_OBJECT (EArmObjGicItsInfo, PlatformRepo->GicItsInfo);

    default: {
      Status = EFI_NOT_FOUND;
      DEBUG ((
        DEBUG_WARN,
        "WARNING: Object 0x%x. Status = %r\n",
        CmObjectId,
        Status
        ));
      break;
    }
  }//switch

  return Status;
}

/** Return an OEM namespace object.

    @param [in]  This        Poiner to the Configuration Manager Protocol.
    @param [in]  CmObjectId  The Configuration Manager Object ID.
    @param [out] CmObject    Pointer to the Configuration Manager Object
                             descrptor describing the requested Object.

    @retval Returns:
      EFI_SUCCESS           Success.
      EFI_INVALID_PARAMETER A parameter is invalid.
      EFI_NOT_FOUND         The required object information is not found.
      EFI_BAD_BUFFER_SIZE   The size returned by the Configuration Manager
                            is less than the Object size for the requested
                            object.
*/
EFI_STATUS
EFIAPI
GetOemNameSpaceObject (
  IN  CONST EFI_CONFIGURATION_MANAGER_PROTOCOL  * CONST This,
  IN  CONST CM_OBJECT_ID                                CmObjectId,
  IN  OUT   CM_OBJ_DESCRIPTOR                   * CONST CmObject
  )
{
  EFI_STATUS  Status = EFI_SUCCESS;

  if ((This == NULL) || (CmObject == NULL)) {
    ASSERT (This != NULL);
    ASSERT (CmObject != NULL);
    return EFI_INVALID_PARAMETER;
  }

  switch (GET_CM_OBJECT_ID (CmObjectId)) {
    default: {
      Status = EFI_NOT_FOUND;
      DEBUG ((
        DEBUG_ERROR,
        "ERROR: Object 0x%x, Status = %r\n",
        CmObjectId,
        Status
        ));
      break;
    }
  }

  return Status;
}

/** The GetObject function defines the interface implemented by the
    Configuration Manager Protocol for returning the Configuration
    Manager Objects.

    @param [in]  This        Poiner to the Configuration Manager Protocol.
    @param [in]  CmObjectId  The Configuration Manager Object ID.
    @param [out] CmObject    Pointer to the Configuration Manager Object
                             descrptor describing the requested Object.

    @retval Returns:
      EFI_SUCCESS           Success.
      EFI_INVALID_PARAMETER A parameter is invalid.
      EFI_NOT_FOUND         The required object information is not found.
*/
EFI_STATUS
EFIAPI
ArmVExpressPlatformGetObject (
  IN  CONST EFI_CONFIGURATION_MANAGER_PROTOCOL  * CONST This,
  IN  CONST CM_OBJECT_ID                                CmObjectId,
  IN  OUT   CM_OBJ_DESCRIPTOR                   * CONST CmObject
  )
{
  EFI_STATUS  Status;

  if ((This == NULL) || (CmObject == NULL)) {
    ASSERT (This != NULL);
    ASSERT (CmObject != NULL);
    return EFI_INVALID_PARAMETER;
  }

  switch (GET_CM_NAMESPACE_ID (CmObjectId)) {
    case EObjNameSpaceStandard:
      Status = GetStandardNameSpaceObject (This, CmObjectId, CmObject);
      break;
    case EObjNameSpaceArm:
      Status = GetArmNameSpaceObject (This, CmObjectId, CmObject);
      break;
    case EObjNameSpaceOem:
      Status = GetOemNameSpaceObject (This, CmObjectId, CmObject);
      break;
    default: {
      Status = EFI_INVALID_PARAMETER;
      DEBUG ((
        DEBUG_ERROR,
        "ERROR: Unknown Namespace Object = 0x%x, Status = %r\n",
        CmObjectId,
        Status
        ));
      break;
    }
  }

  return Status;
}

/** The SetObject function defines the interface implemented by the
    Configuration Manager Protocol for updating the Configuration
    Manager Objects.

    @param [in]  This        Poiner to the Configuration Manager Protocol.
    @param [in]  CmObjectId  The Configuration Manager Object ID.
    @param [out] CmObject    Pointer to the Configuration Manager Object
                             descrptor describing the Object.

    @retval Returns:
      EFI_UNSUPPORTED       This operation is not supported.
*/
EFI_STATUS
EFIAPI
ArmVExpressPlatformSetObject (
  IN  CONST EFI_CONFIGURATION_MANAGER_PROTOCOL  * CONST This,
  IN  CONST CM_OBJECT_ID                                CmObjectId,
  IN        CM_OBJ_DESCRIPTOR                   * CONST CmObject
  )
{
  return EFI_UNSUPPORTED;
}

/** A structure describing the configuration manager protocol interface.
*/
STATIC
CONST
EFI_CONFIGURATION_MANAGER_PROTOCOL ArmVExpressPlatformConfigurationManagerProtocol = {
  CREATE_REVISION(1,0),
  ArmVExpressPlatformGetObject,
  ArmVExpressPlatformSetObject,
  &ArmVExpressPlatformRepositoryInfo
};

/**
  Entrypoint of Configuration Manager Dxe.

  @param  ImageHandle
  @param  SystemTable

  @return EFI_SUCCESS
  @return EFI_LOAD_ERROR
  @return EFI_OUT_OF_RESOURCES

**/
EFI_STATUS
EFIAPI
ConfigurationManagerDxeInitialize (
  IN EFI_HANDLE          ImageHandle,
  IN EFI_SYSTEM_TABLE  * SystemTable
  )
{
  EFI_STATUS  Status;

  Status = gBS->InstallProtocolInterface (
                  &ImageHandle,
                  &gEfiConfigurationManagerProtocolGuid,
                  EFI_NATIVE_INTERFACE,
                  (VOID*)&ArmVExpressPlatformConfigurationManagerProtocol
                  );
  if (EFI_ERROR (Status)) {
    DEBUG ((
      DEBUG_ERROR,
      "ERROR: Failed to get Install Configuration Manager Protocol." \
      " Status = %r\n",
      Status
      ));
    goto error_handler;
  }

  Status = InitializePlatformRepository (
    &ArmVExpressPlatformConfigurationManagerProtocol
    );
  if (EFI_ERROR (Status)) {
    DEBUG ((
      DEBUG_ERROR,
      "ERROR: Failed to initialize the Platform Configuration Repository." \
      " Status = %r\n",
      Status
      ));
  }

error_handler:
  return Status;
}
